# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts --production

# Copy source code and OpenAPI spec
COPY src ./src

# Set environment
ENV NODE_ENV=production

# Default command to run the MCP server over stdio
CMD ["node", "src/mailgun-mcp.js"]
